fix build error caused by empty spec.bs
All builds now failed with the error below:

FATAL ERROR: The document requires at least one &lt;pre class=metadata> block.
 ✘  Did not generate, due to fatal errors
make[1]: *** [Makefile:10: spec.html] Error 22
make: *** [Makefile:26: ci] Error 2

It seems to be due to the spec.bs being empty, but at least one <pre class="metadata"> block is required.